[package]
name = "eggersmann_app_server_auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "91f6288", features=['json'] }
serde = { version = "~1", features = ["derive"] }
azure_security_keyvault = "~0"
azure_identity = "~0"
jsonwebtoken = "~8"
reqwest = { version = "~0", features = ["cookies", "blocking", "json", "rustls-tls"] }
serde_json = "~1"
playwright = "~0"
chrono = "~0"
rand = "~0"
sha2 = "~0"
url = "~2"